import { dirname } from 'path';
import { fileURLToPath } from 'url';
import { FlatCompat } from '@eslint/eslintrc';

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

const config = [
    // next-env.d.ts is generated by Next on every build.
    { ignores: ['.next/**', 'node_modules/**', 'next-env.d.ts'] },
    ...compat.extends('next/core-web-vitals', 'next/typescript'),
    {
        rules: {
            // The gallery ships its own pre-sized 900px and 1200px JPEGs, so
            // next/image has nothing to add and would only add a proxy hop.
            '@next/next/no-img-element': 'off',
        },
    },
];

export default config;
