import coreWebVitals from 'eslint-config-next/core-web-vitals';
import nextTypescript from 'eslint-config-next/typescript';

// Imported straight in, with no `FlatCompat` around them. Up to eslint-config-next
// 15 these were eslintrc-style presets that had to be converted; from 16 the
// package exports flat config arrays itself, and putting the compat shim back in
// front of them fails outright — it tries to JSON.stringify a config that now
// holds circular plugin references.
const config = [
    // next-env.d.ts is generated by Next on every build.
    { ignores: ['.next/**', 'node_modules/**', 'next-env.d.ts'] },
    ...coreWebVitals,
    ...nextTypescript,
    {
        rules: {
            // The gallery ships its own pre-sized 900px and 1200px JPEGs, so
            // next/image has nothing to add and would only add a proxy hop.
            '@next/next/no-img-element': 'off',
        },
    },
];

export default config;
